name: Deploy db

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: jdbc:postgresql://myburger-db-server-do-user-17490961-0.l.db.ondigitalocean.com:25060/my_burger
      DATABASE_USER: doadmin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_ACCESS }}
      
      - name: Get userpassword
        run: |
          DB_ID=$(doctl databases list --format ID --no-header)
          DB_PASS=$(doctl databases user get $DB_ID doadmin --format Password --no-header)
          echo "DB_PASS=$DB_PASS" >> $GITHUB_ENV

      - name: run gradle
        env:
          DATABASE_PASSWORD: ${{ env.DB_PASS }}
        run: |
          apt-get update -y
          apt-get upgrade -y
          apt-get install openjdk-21-jdk -y
          wget https://services.gradle.org/distributions/gradle-8.9-bin.zip
          mkdir /opt/gradle
          unzip gradle-8.9-bin.zip
          export PATH=$PATH:/opt/gradle/gradle-8.10.2/bin
          ./gradlew --no-daemon update
