name: Deploy db

on:
  workflow_dispatch:
  push:
    branches:
      - update-ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_USER: doadmin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_ACCESS }}

      - name: Get userpassword
        run: |
          DB_ID=$(doctl db list | grep pg | awk '{print $1}')
          DB_PASS=$(doctl databases user get $DB_ID doadmin --format Password --no-header)
          DB_HOST=$(doctl databases connection $DB_ID --format Host --no-header)
          DB_PORT=$(doctl databases connection $DB_ID --format Port --no-header)
          echo "DB_PASS=$DB_PASS" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: run gradle
        env:
          DATABASE_PASSWORD: ${{ env.DB_PASS }}
          DATABASE_HOST: ${{env.DB_HOST}}
          DATABASE_PORT: ${{env.DB_PORT}}
        run: |
          echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
          echo "DATABASE_HOST=${DATABASE_HOST}"
          echo "DATABASE_PORT=${DATABASE_PORT}"
          sed 's/#DB_PASS#/'"$DATABASE_PASSWORD"'/g' -i .env
          sed 's/#DB_HOST#/'"$DATABASE_HOST"'/g' -i .env
          sed 's/#DB_PORT#/'"$DATABASE_PORT"'/g' -i .env
          ./gradlew --no-daemon update
